# -*- coding: utf-8 -*-
"""botpitonico.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWf05SGEGoWOex6L6LvMREbr1-pAdBuc
"""



def usuario (): #Define la función llamada usuario
    nombre = input("Por favor ingrese su nombre: ") #Input genera un espacio de texto donde el usuario responda una pregunta
    print(f"Hola, {nombre}! Encantado de conocerte.") #Print {nombre} se refiere a que el bot responda con el nombre que el usuario le dió. La f se refiere a que la variable va a ser insertada y que no salga {nombre}, sino {Gabriel} o {Elmer}.
    print() #Hace que aparezca un espacio
    print(f"¿En qué te puedo ayudar, {nombre}?") #Misma cosa.

usuario()